export const siteConfig = {
  name: 'Lin',
  shortName: 'LIN',
  title: 'Lin / Lab Notes',
  brand: 'LIN / LAB NOTES',
  description: '记录研究、工程、写作与日常的个人数字花园。',
  siteUrl: 'https://linyeegiong.github.io',
  locale: 'zh-CN',
  timezone: 'Asia/Shanghai',
  location: 'SHANGHAI / UTC+8',
  github: 'https://github.com/LinYeeGiong',
  repository: 'https://github.com/LinYeeGiong/LinYeeGiong.github.io',
  email: null,
  hero: {
    overline: 'Research · Code · Everyday',
    headlineTop: '把世界',
    headlineBeforeAccent: '写成',
    headlineAccent: '笔记',
    intro: '我记录正在学习的技术、实验里发生的问题，以及那些值得慢慢想清楚的日常。这里不是简历，是一份持续更新的个人档案。',
    cta: '进入我的世界',
    ctaHref: '/about/',
  },
  navigation: [
    { label: '首页', href: '/' },
    { label: '关于', href: '/about/' },
    { label: '学习', href: '/notes/' },
    { label: '随笔', href: '/essays/' },
    { label: 'Daily', href: '/daily/' },
  ],
  terminal: {
    user: 'lin',
    host: 'lab',
    shellTitle: 'lin@garden — zsh',
    session: 'SESSION 01',
    placeholder: 'try /explore',
    welcome: 'routes: /about /notes /essays /daily /explore · /clear',
    shortcuts: ['/about', '/notes', '/essays', '/daily', '/explore'],
  },
  exploration: [
    { id: 'agents', label: 'AI AGENTS', title: '智能体与协作', description: '记录 Agent Memory、工具调用，以及人如何与 AI 共同完成长期工作。', href: '/notes/', tags: ['AI', 'Agent'] },
    { id: 'systems', label: '系统', title: '系统与工程', description: '从实验环境到稳定部署，留下故障、取舍和可复用的工程判断。', href: '/notes/', tags: ['系统', '工程'] },
    { id: 'writing', label: '写作', title: '写作与思考', description: '用公开写作整理尚未完成的想法，也记录观点如何随时间改变。', href: '/essays/', tags: ['写作', '思考'] },
    { id: 'reading', label: '阅读', title: '阅读与摘记', description: '不只收藏答案：重述一本书，连接旧问题，再形成自己的判断。', href: '/notes/', tags: ['阅读', '书摘'] },
    { id: 'life', label: '生活影像', title: '生活与影像', description: '实验室、街道、光线和微小日常，构成技术之外的生活切片。', href: '/daily/', tags: ['Daily', '生活', '影像'] },
  ],
  footer: {
    copyright: 'LIN',
    links: [
      { label: 'GITHUB', href: 'https://github.com/LinYeeGiong', external: true },
      { label: 'RSS', href: '/rss.xml', external: false },
      { label: 'TOP ↑', href: '#top', external: false },
    ],
  },
} as const;
